// apps/kitchen-sink/shared/vue/components/Sidebar.vue
<script setup lang="ts">
import { Bell, LogOut } from 'lucide-vue-next'
import { Deferred, Link, usePage } from 'nestjs-mvc/vue'
import { computed } from 'vue'
import { navigation } from '../../navigation'
import NavGroupItem from './NavGroupItem.vue'
import { icons, isActive } from './navigation'

const page = usePage<{
  auth?: {
    user?: { name: string; email: string } | null
    notifications?: { id: number; body: string }[]
  }
}>()

const user = computed(() => page.props.auth?.user)
const notifications = computed(() => page.props.auth?.notifications)
const initials = computed(() =>
  (user.value?.name ?? '')
    .split(' ')
    .map((part) => part[0])
    .join(''),
)
</script>

<template>
  <aside class="flex w-72 shrink-0 flex-col border-r border-slate-200 bg-white">
    <div class="flex items-center gap-2 px-5 py-5">
      <span class="grid size-8 place-items-center rounded-lg bg-blue-600 font-bold text-white">N</span>
      <span class="font-semibold text-slate-900">NestJS MVC</span>

      <!-- Nested deferred prop: announced as `auth.notifications` and fetched
           after the first paint. Proves dot-notation works end to end. -->
      <Deferred data="auth.notifications">
        <template #fallback>
          <span class="ml-auto size-4 animate-pulse rounded-full bg-slate-200" />
        </template>
        <span class="ml-auto flex items-center gap-1 text-xs text-slate-500" :title="`${notifications?.length ?? 0} recent notes by you`">
          <Bell class="size-4" />
          {{ notifications?.length ?? 0 }}
        </span>
      </Deferred>
    </div>

    <nav class="flex-1 overflow-y-auto px-3 pb-4">
      <div v-for="section in navigation" :key="section.label" class="mb-6">
        <p class="px-3 pb-2 text-xs font-medium tracking-wide text-slate-500">{{ section.label }}</p>
        <ul class="space-y-0.5">
          <template v-for="group in section.groups" :key="group.label">
            <li v-if="group.href">
              <Link
                :href="group.href"
                :class="[
                  'flex items-center gap-3 rounded-lg px-3 py-2 text-sm',
                  isActive(page.url, group.href) ? 'bg-blue-50 font-medium text-blue-700' : 'text-slate-700 hover:bg-slate-100',
                ]"
              >
                <component
                  :is="icons[group.icon]"
                  :class="['size-4 shrink-0', isActive(page.url, group.href) ? 'text-blue-600' : 'text-slate-500']"
                />
                {{ group.label }}
              </Link>
            </li>
            <NavGroupItem v-else :group="group" :current-url="page.url" />
          </template>
        </ul>
      </div>
    </nav>

    <div v-if="user" class="flex items-center gap-3 border-t border-slate-200 px-5 py-4">
      <span class="grid size-8 place-items-center rounded-full bg-slate-200 text-xs font-semibold text-slate-600">{{ initials }}</span>
      <div class="min-w-0 flex-1">
        <p class="truncate text-sm font-medium text-slate-900">{{ user.name }}</p>
        <p class="truncate text-xs text-slate-500">{{ user.email }}</p>
      </div>
      <!-- A POST, so a link from another site cannot log you out. -->
      <Link
        href="/logout"
        method="post"
        as="button"
        title="Log out"
        class="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100 hover:text-slate-900"
      >
        <LogOut class="size-4" />
        <span class="sr-only">Log out</span>
      </Link>
    </div>
    <div v-else class="flex gap-2 border-t border-slate-200 px-5 py-4 text-sm">
      <Link href="/login" class="rounded-lg bg-blue-600 px-3 py-1.5 font-medium text-white hover:bg-blue-700">Log in</Link>
      <Link href="/register" class="rounded-lg px-3 py-1.5 text-slate-700 hover:bg-slate-100">Register</Link>
    </div>
  </aside>
</template>

// apps/kitchen-sink/frontend/components/Sidebar.tsx
import { Deferred, Link, usePage } from 'nestjs-mvc/react'
import { Bell, ChevronRight, LogOut } from 'lucide-react'
import { useState } from 'react'
import { navigation, type NavGroup } from '../navigation'

function isActive(currentUrl: string, href?: string): boolean {
  if (!href) return false
  return currentUrl === href || currentUrl.startsWith(`${href}/`)
}

function CollapsibleGroup({ group, currentUrl }: { group: NavGroup; currentUrl: string }) {
  const hasActiveChild = group.items?.some((item) => isActive(currentUrl, item.href)) ?? false
  const [open, setOpen] = useState(hasActiveChild)
  const Icon = group.icon

  return (
    <li>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm text-slate-700 hover:bg-slate-100"
      >
        <Icon className="size-4 shrink-0 text-slate-500" />
        <span className="flex-1 text-left">{group.label}</span>
        <ChevronRight className={`size-4 text-slate-400 transition-transform ${open ? 'rotate-90' : ''}`} />
      </button>

      {open && (
        <ul className="mt-1 ml-7 space-y-0.5 border-l border-slate-200 pl-3">
          {group.items?.map((item) =>
            item.href ? (
              <li key={item.label}>
                <Link
                  href={item.href}
                  className={`block rounded-md px-2 py-1.5 text-sm ${
                    isActive(currentUrl, item.href)
                      ? 'bg-blue-50 font-medium text-blue-700'
                      : 'text-slate-600 hover:bg-slate-100'
                  }`}
                >
                  {item.label}
                </Link>
              </li>
            ) : (
              <li
                key={item.label}
                title="Not built yet"
                className="cursor-not-allowed px-2 py-1.5 text-sm text-slate-400"
              >
                {item.label}
              </li>
            ),
          )}
        </ul>
      )}
    </li>
  )
}

export function Sidebar() {
  const { url, props } = usePage<{
    auth?: {
      user?: { name: string; email: string } | null
      notifications?: { id: number; body: string }[]
    }
  }>()
  const user = props.auth?.user
  const notifications = props.auth?.notifications

  return (
    <aside className="flex w-72 shrink-0 flex-col border-r border-slate-200 bg-white">
      <div className="flex items-center gap-2 px-5 py-5">
        <span className="grid size-8 place-items-center rounded-lg bg-blue-600 font-bold text-white">
          N
        </span>
        <span className="font-semibold text-slate-900">NestJS MVC</span>

        {/* Nested deferred prop: announced as `auth.notifications` and fetched
            after the first paint. Proves dot-notation works end to end. */}
        <Deferred
          data="auth.notifications"
          fallback={<span className="ml-auto size-4 animate-pulse rounded-full bg-slate-200" />}
        >
          <span
            className="ml-auto flex items-center gap-1 text-xs text-slate-500"
            title={`${notifications?.length ?? 0} recent notes by you`}
          >
            <Bell className="size-4" />
            {notifications?.length ?? 0}
          </span>
        </Deferred>
      </div>

      <nav className="flex-1 overflow-y-auto px-3 pb-4">
        {navigation.map((section) => (
          <div key={section.label} className="mb-6">
            <p className="px-3 pb-2 text-xs font-medium tracking-wide text-slate-500">{section.label}</p>
            <ul className="space-y-0.5">
              {section.groups.map((group) =>
                group.href ? (
                  <li key={group.label}>
                    <Link
                      href={group.href}
                      className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm ${
                        isActive(url, group.href)
                          ? 'bg-blue-50 font-medium text-blue-700'
                          : 'text-slate-700 hover:bg-slate-100'
                      }`}
                    >
                      <group.icon
                        className={`size-4 shrink-0 ${isActive(url, group.href) ? 'text-blue-600' : 'text-slate-500'}`}
                      />
                      {group.label}
                    </Link>
                  </li>
                ) : (
                  <CollapsibleGroup key={group.label} group={group} currentUrl={url} />
                ),
              )}
            </ul>
          </div>
        ))}
      </nav>

      {user ? (
        <div className="flex items-center gap-3 border-t border-slate-200 px-5 py-4">
          <span className="grid size-8 place-items-center rounded-full bg-slate-200 text-xs font-semibold text-slate-600">
            {user.name
              .split(' ')
              .map((part) => part[0])
              .join('')}
          </span>
          <div className="min-w-0 flex-1">
            <p className="truncate text-sm font-medium text-slate-900">{user.name}</p>
            <p className="truncate text-xs text-slate-500">{user.email}</p>
          </div>
          {/* A POST, so a link from another site cannot log you out. */}
          <Link
            href="/logout"
            method="post"
            as="button"
            title="Log out"
            className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100 hover:text-slate-900"
          >
            <LogOut className="size-4" />
            <span className="sr-only">Log out</span>
          </Link>
        </div>
      ) : (
        <div className="flex gap-2 border-t border-slate-200 px-5 py-4 text-sm">
          <Link href="/login" className="rounded-lg bg-blue-600 px-3 py-1.5 font-medium text-white hover:bg-blue-700">
            Log in
          </Link>
          <Link href="/register" className="rounded-lg px-3 py-1.5 text-slate-700 hover:bg-slate-100">
            Register
          </Link>
        </div>
      )}
    </aside>
  )
}
